### ISSUE TITLE
Добавить уровни пользователей

### ISSUE THREAD

**Issue by dmitryzuev** [Mazzz/tiny-cat#4]
Необходимо реализовать возможность разного уровня доступа для пользователей:
1. Админ
2. Владелец котофермы
3. Гость

**Администраторы**
При регистрации должны указать имя, фамилию, email, пароль не короче 10 символов, аватарку, фото паспорта, дату рождения.

**Владельцы котоферм**
При регистрации должны указать название котофермы, email, пароль не короче 8 символов, аватарку.

**Гости**
Для регистрации должны ввести email и пароль не короче 6 символов.

**Comment by dmitryzuev** [comment]
Название котофермы следует указывать после #5

**Comment by Mazzz** [comment]
#7
